default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  timeout: 5000

test:
  <<: *default
  database: ourmaps_api_test

development:
  <<: *default
  database: ourmaps_api_development

production:
  <<: *default
  database: ourmaps_api_production