# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv'
gem 'pg'
gem 'puma'
gem 'rack-unreloader'
gem 'rackup'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'
gem "rack", "~> 3.1"
gem "sinatra-contrib", "~> 4.0"
gem "uuid", "~> 2.3"

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem "database_cleaner", "~> 2.0"
end

group :development do
  gem 'byebug'
end
