# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv'
gem 'puma'
gem 'rackup'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord'

group :test do
  gem 'sqlite3'
  gem 'rack-test'
  gem 'rspec'
end

group :development, :production do
  gem 'pg'
  gem 'byebug'
end
